"""empty message

Revision ID: 20898dfd646c
Revises: f04e59224815
Create Date: 2017-11-06 10:19:23.726726

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '20898dfd646c'
down_revision = 'f04e59224815'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('participant', sa.Column('title', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('participant', 'title')
    # ### end Alembic commands ###
