"""empty message

Revision ID: 286e70743050
Revises: 4f81c8a8604f
Create Date: 2017-12-11 13:51:22.954768

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '286e70743050'
down_revision = '4f81c8a8604f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('session', sa.Column('max_days_prior', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('session', 'max_days_prior')
    # ### end Alembic commands ###
