"""empty message

Revision ID: 30fe0e82d100
Revises: d21b7288ec04
Create Date: 2017-09-14 15:47:02.032628

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '30fe0e82d100'
down_revision = 'd21b7288ec04'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('session', sa.Column('location', sa.TEXT(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('session', 'location')
    # ### end Alembic commands ###
