"""empty message

Revision ID: 49291e8153f0
Revises: 9e21969537b9
Create Date: 2018-01-04 17:40:40.635208

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '49291e8153f0'
down_revision = '9e21969537b9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('email_log', sa.Column('error', sa.TEXT(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('email_log', 'error')
    # ### end Alembic commands ###
