"""empty message

Revision ID: 4f81c8a8604f
Revises: e5b7290c6335
Create Date: 2017-11-19 13:16:31.530787

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4f81c8a8604f'
down_revision = 'e5b7290c6335'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('workshop', sa.Column('discourse_enabled', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('workshop', 'discourse_enabled')
    # ### end Alembic commands ###
