"""empty message

Revision ID: 4f9801c12860
Revises: f44f80d639e9
Create Date: 2017-12-13 16:24:34.214983

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4f9801c12860'
down_revision = 'f44f80d639e9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('workshop_followers',
    sa.Column('workshop_id', sa.Integer(), nullable=True),
    sa.Column('participant_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['participant_id'], ['participant.id'], ),
    sa.ForeignKeyConstraint(['workshop_id'], ['workshop.id'], )
    )
    op.drop_column('participant_session', 'wait_listed')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('participant_session', sa.Column('wait_listed', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.drop_table('workshop_followers')
    # ### end Alembic commands ###
