"""empty message

Revision ID: 88103012e2a4
Revises: 4f9801c12860
Create Date: 2017-12-20 14:21:32.891799

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '88103012e2a4'
down_revision = '4f9801c12860'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('email_message', sa.Column('workshop_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'email_message', 'workshop', ['workshop_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'email_message', type_='foreignkey')
    op.drop_column('email_message', 'workshop_id')
    # ### end Alembic commands ###
