"""empty message

Revision ID: a1ec13146cfe
Revises: 9adc0e883fc8
Create Date: 2017-09-06 15:59:39.135697

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a1ec13146cfe'
down_revision = '9adc0e883fc8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('participant', sa.Column('uid', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('participant', 'uid')
    # ### end Alembic commands ###
