"""empty message

Revision ID: b1a2f01d072a
Revises: e1b57010d53f
Create Date: 2017-11-01 14:22:40.244764

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b1a2f01d072a'
down_revision = 'e1b57010d53f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('track', sa.Column('sub_title', sa.TEXT(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('track', 'sub_title')
    # ### end Alembic commands ###
