"""empty message

Revision ID: c4a1980ace52
Revises: 49291e8153f0
Create Date: 2018-06-26 10:01:57.922504

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c4a1980ace52'
down_revision = '49291e8153f0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('track', sa.Column('featured', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('track', 'featured')
    # ### end Alembic commands ###
