"""empty message

Revision ID: cfc0359a9884
Revises: cd8ac737a10c
Create Date: 2017-09-22 14:28:58.515545

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cfc0359a9884'
down_revision = 'cd8ac737a10c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('email_log', sa.Column('date_opened', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('email_log', 'date_opened')
    # ### end Alembic commands ###
