"""empty message

Revision ID: d911d67fa2d4
Revises: df361a922e41
Create Date: 2017-10-26 16:44:05.082980

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd911d67fa2d4'
down_revision = 'df361a922e41'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('participant', sa.Column('role', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('participant', 'role')
    # ### end Alembic commands ###
