"""empty message

Revision ID: e1b57010d53f
Revises: 91a1129e95d5
Create Date: 2017-10-30 14:09:47.603223

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e1b57010d53f'
down_revision = '91a1129e95d5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('participant_session', 'is_instructor')
    op.add_column('workshop', sa.Column('instructor_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'workshop', 'participant', ['instructor_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'workshop', type_='foreignkey')
    op.drop_column('workshop', 'instructor_id')
    op.add_column('participant_session', sa.Column('is_instructor', sa.BOOLEAN(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
