"""empty message

Revision ID: e5b7290c6335
Revises: 20898dfd646c
Create Date: 2017-11-14 21:39:07.834558

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e5b7290c6335'
down_revision = '20898dfd646c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('workshop', sa.Column('discourse_topic_id', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('workshop', 'discourse_topic_id')
    # ### end Alembic commands ###
