"""empty message

Revision ID: f04e59224815
Revises: b1a2f01d072a
Create Date: 2017-11-02 10:34:10.008049

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f04e59224815'
down_revision = 'b1a2f01d072a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('code', sa.Column('description', sa.TEXT(), nullable=True))
    op.drop_column('code', 'desc')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('code', sa.Column('desc', sa.TEXT(), autoincrement=False, nullable=True))
    op.drop_column('code', 'description')
    # ### end Alembic commands ###
