"""empty message

Revision ID: f31f4ef9b425
Revises: 88103012e2a4
Create Date: 2017-12-21 13:40:48.072863

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f31f4ef9b425'
down_revision = '88103012e2a4'
branch_labels = None
depends_on = None


def upgrade():
    op.drop_table('email_log')
    op.create_table('email_log',
    sa.Column('participant_id', sa.Integer(), nullable=False),
    sa.Column('email_message_id', sa.Integer(), nullable=False),
    sa.Column('tracking_code', sa.String(), nullable=True),
    sa.Column('opened', sa.Boolean(), nullable=True),
    sa.Column('date_sent', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=True),
    sa.Column('type', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['email_message_id'], ['email_message.id'], ),
    sa.ForeignKeyConstraint(['participant_id'], ['participant.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_foreign_key(None, 'email_log', 'session', ['session_id'], ['id'])


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('email_log')
    op.create_table('email_log',
                    sa.Column('participant_id', sa.Integer(), nullable=False),
                    sa.Column('email_message_id', sa.Integer(), nullable=False),
                    sa.Column('tracking_code', sa.String(), nullable=True),
                    sa.Column('opened', sa.Boolean(), nullable=True),
                    sa.ForeignKeyConstraint(['email_message_id'], ['email_message.id'], ),
                    sa.ForeignKeyConstraint(['participant_id'], ['participant.id'], ),
                    sa.PrimaryKeyConstraint('participant_id', 'email_message_id')
                    )
