"""empty message

Revision ID: f44f80d639e9
Revises: 286e70743050
Create Date: 2017-12-12 18:02:59.981287

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f44f80d639e9'
down_revision = '286e70743050'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'participant', ['uid'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'participant', type_='unique')
    # ### end Alembic commands ###
